services:
  jupyter-lab:
    image: tsingh98/wine_quality_predictor_group1:cd1bccc
    ports:
      - "8888:8888"
    volumes:
      - .:/home/jovyan
    deploy:
      resources:
        limits:
          memory: 5G
    platform: linux/amd64
