name: '522_group1'
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - pandas=2.2.3
  - numpy=2.1.3
  - seaborn=0.13.2
  - scipy=1.14.1
  - matplotlib=3.9.2
  - scikit-learn=1.5.2
  - conda-lock=2.5.7
  - pandera=0.20.4
  - jupyterlab=4.3.1
  - tabulate=0.9.0
  - quarto=1.5.57
  - click=8.1.7